// Icon mapping utility to resolve icon names to components
// This allows passing icon names as strings from Server Components to Client Components

import {
  Shield,
  Target,
  Users,
  Award,
  TrendingUp,
  Globe,
  CheckCircle2,
  CheckCircle,
  ArrowRight,
  Calendar,
  Rocket,
  Heart,
  Lightbulb,
  Zap,
  Lock,
  Quote,
  Mail,
  Linkedin,
  Clock,
  Eye,
  Check,
  AlertTriangle,
  AlertCircle,
  Search,
  SearchCheck,
  Code,
  Database,
  Server,
  FileText,
  FileSearch,
  FileCheck2,
  BarChart,
  BarChart3,
  Settings,
  BookOpen,
  Newspaper,
  Video,
  FileCheck,
  Star,
  RefreshCcw,
  Home,
  Gift,
  Building2,
  Download,
  Phone,
  MapPin,
  GraduationCap,
  Send,
  Facebook,
  Instagram,
  Youtube,
  Github,
  User,
  Bug,
  type LucideIcon
} from "lucide-react";
import { RiTwitterXFill } from "react-icons/ri";
import type { IconType } from "react-icons";

export const iconMap: Record<string, LucideIcon | IconType> = {
  Shield,
  Target,
  Users,
  Award,
  TrendingUp,
  Globe,
  CheckCircle2,
  CheckCircle,
  ArrowRight,
  Calendar,
  Rocket,
  Heart,
  Lightbulb,
  Zap,
  Lock,
  Quote,
  Mail,
  Linkedin,
  TwitterX: RiTwitterXFill, // X (formerly Twitter)
  Clock,
  Eye,
  Check,
  AlertTriangle,
  AlertCircle,
  Search,
  SearchCheck,
  Code,
  Database,
  Server,
  FileText,
  FileSearch,
  FileCheck2,
  BarChart,
  BarChart3,
  Settings,
  BookOpen,
  Newspaper,
  Video,
  FileCheck,
  Star,
  RefreshCcw,
  Home,
  Gift,
  Building2,
  Download,
  Phone,
  MapPin,
  GraduationCap,
  Send,
  Facebook,
  Instagram,
  Youtube,
  Github,
  User,
  Bug,
};

export type IconName = keyof typeof iconMap;

export function getIcon(name: IconName): LucideIcon | IconType {
  return iconMap[name];
}
