CREATE TYPE "public"."event_status" AS ENUM('draft', 'upcoming', 'live', 'completed', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."event_type" AS ENUM('webinar', 'workshop', 'conference', 'meetup', 'training');--> statement-breakpoint
CREATE TYPE "public"."appointment_status" AS ENUM('pending', 'confirmed', 'completed', 'cancelled', 'no_show', 'rescheduled');--> statement-breakpoint
CREATE TYPE "public"."appointment_type" AS ENUM('consultation', 'demo', 'discovery', 'follow_up', 'support', 'training');--> statement-breakpoint
CREATE TABLE "event_registrations" (
	"id" text PRIMARY KEY NOT NULL,
	"event_id" text NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text,
	"company" text,
	"job_title" text,
	"attended" boolean DEFAULT false NOT NULL,
	"cancelled_at" timestamp,
	"reminder_sent" boolean DEFAULT false NOT NULL,
	"follow_up_sent" boolean DEFAULT false NOT NULL,
	"source" text,
	"registered_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"slug" text NOT NULL,
	"description" text NOT NULL,
	"short_description" text,
	"type" "event_type" DEFAULT 'webinar' NOT NULL,
	"status" "event_status" DEFAULT 'draft' NOT NULL,
	"start_date" timestamp NOT NULL,
	"end_date" timestamp,
	"timezone" text DEFAULT 'Asia/Kolkata' NOT NULL,
	"duration" integer,
	"is_virtual" boolean DEFAULT true NOT NULL,
	"location" text,
	"meeting_url" text,
	"meeting_id" text,
	"meeting_password" text,
	"cover_image" text,
	"thumbnail_image" text,
	"recording_url" text,
	"speakers" jsonb DEFAULT '[]'::jsonb,
	"requires_registration" boolean DEFAULT true NOT NULL,
	"max_attendees" integer,
	"registration_deadline" timestamp,
	"agenda" jsonb DEFAULT '[]'::jsonb,
	"topics" jsonb DEFAULT '[]'::jsonb,
	"target_audience" text,
	"featured" boolean DEFAULT false NOT NULL,
	"display_order" integer DEFAULT 0 NOT NULL,
	"meta_title" text,
	"meta_description" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"published_at" timestamp,
	CONSTRAINT "events_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "appointments" (
	"id" text PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"type" "appointment_type" DEFAULT 'consultation' NOT NULL,
	"status" "appointment_status" DEFAULT 'pending' NOT NULL,
	"scheduled_at" timestamp NOT NULL,
	"duration" integer DEFAULT 30 NOT NULL,
	"timezone" text DEFAULT 'Asia/Kolkata' NOT NULL,
	"client_name" text NOT NULL,
	"client_email" text NOT NULL,
	"client_phone" text,
	"client_company" text,
	"client_job_title" text,
	"is_virtual" boolean DEFAULT true NOT NULL,
	"meeting_url" text,
	"meeting_id" text,
	"location" text,
	"assigned_to" text,
	"assigned_email" text,
	"service_interest" text,
	"lead_source" text,
	"client_notes" text,
	"internal_notes" text,
	"meeting_notes" text,
	"reminder_sent_at" timestamp,
	"follow_up_sent_at" timestamp,
	"original_scheduled_at" timestamp,
	"rescheduled_count" integer DEFAULT 0 NOT NULL,
	"cancel_reason" text,
	"calendly_event_uri" text,
	"calendly_invitee_uri" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"confirmed_at" timestamp,
	"completed_at" timestamp,
	"cancelled_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "event_registrations" ADD CONSTRAINT "event_registrations_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;